name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub IP and Open Firewall
        run: |
          GITHUB_IP=$(curl -s https://api.ipify.org)
          echo "GITHUB_IP=$GITHUB_IP" >> $GITHUB_ENV
          echo "Opening firewall for $GITHUB_IP"
          aws ec2 authorize-security-group-ingress \
            --group-id "${{ secrets.SG_ID }}" \
            --protocol tcp \
            --port 22 \
            --cidr ${GITHUB_IP}/32 || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/local/bin
            cd /home/ubuntu/testing-purose
            git fetch origin
            git reset --hard origin/master
            sudo chown -R ubuntu:ubuntu /home/ubuntu/testing-purose/backend
            pm2 stop app || true
            pm2 start /home/ubuntu/testing-purose/backend/app.js --name app
            pm2 save
            echo "Backend deployed successfully!"

      - name: Remove IP from Firewall
        if: always()
        run: |
          echo "Closing firewall for $GITHUB_IP"
          aws ec2 revoke-security-group-ingress \
            --group-id "${{ secrets.SG_ID }}" \
            --protocol tcp \
            --port 22 \
            --cidr ${GITHUB_IP}/32 || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
